// app/terms-and-conditions/page.tsx
export default function TermsAndConditions() {
  return (
    <main className="mx-auto max-w-4xl px-6 py-12 text-gray-800">
      <h1 className="text-3xl font-bold mb-6">Terms & Conditions</h1>
      <p className="text-sm text-gray-500 mb-8">Last updated: July 10, 2025</p>

      <section className="mb-10">
        <p>
          Welcome to <strong>Sommario AI</strong> (
          <a
            href="https://sommario-ai.vercel.app"
            className="text-blue-600 underline"
          >
            https://sommario-ai.vercel.app
          </a>
          )!
        </p>
        <p>
          By accessing or using our service, you agree to be bound by these
          Terms & Conditions, including our Privacy and Refund Policies. Please
          read them carefully before using the website or purchasing any product
          or service.
        </p>
      </section>

      <section className="mb-10">
        <h2 className="text-xl font-semibold mb-2">1. Acceptance of Terms</h2>
        <p>
          By using Sommario AI, you confirm that you are at least 18 years old
          or have parental consent and agree to comply with these Terms &
          Conditions.
        </p>
      </section>

      <section className="mb-10">
        <h2 className="text-xl font-semibold mb-2">
          2. Description of Service
        </h2>
        <p>
          Sommario AI provides AI-generated summaries and insights for PDF
          documents. We reserve the right to update, modify, or discontinue any
          part of the service at any time without notice.
        </p>
      </section>

      <section className="mb-10">
        <h2 className="text-xl font-semibold mb-2">3. User Responsibilities</h2>
        <ul className="list-disc list-inside space-y-1">
          <li>
            You may not use the service for illegal, harmful, or abusive
            activities.
          </li>
          <li>
            You are responsible for how you use the summaries and outputs
            generated by the AI.
          </li>
          <li>
            We reserve the right to suspend or terminate your access for
            violations of our policies.
          </li>
        </ul>
      </section>

      <section className="mb-10">
        <h2 className="text-xl font-semibold mb-2">4. Intellectual Property</h2>
        <p>
          All content, features, and functionality of Sommario AI are the
          intellectual property of Sommario AI and its licensors. You may not
          reproduce, distribute, or exploit any part of the platform without
          permission.
        </p>
      </section>

      <section className="mb-10">
        <h2 className="text-xl font-semibold mb-2">
          5. Disclaimer of Warranties
        </h2>
        <p>
          The service is provided “as is” and “as available” without warranties
          of any kind, either express or implied. We do not guarantee the
          accuracy, completeness, or usefulness of any output.
        </p>
      </section>

      <section className="mb-10">
        <h2 className="text-xl font-semibold mb-2">
          6. Limitation of Liability
        </h2>
        <p>
          In no event shall Sommario AI be liable for any indirect, incidental,
          or consequential damages resulting from your use or inability to use
          the service.
        </p>
      </section>

      <section className="mb-10">
        <h2 className="text-xl font-semibold mb-2">7. Refund Policy</h2>
        <p>
          We want you to be completely satisfied with your purchase. If you're
          not happy, you may request a refund within{" "}
          <strong>14 days of your purchase</strong>.
        </p>
        <p className="mt-2">
          Refunds are handled by our reseller{" "}
          <a href="https://www.paddle.com" className="text-blue-600 underline">
            Paddle
          </a>{" "}
          and are considered on a case-by-case basis.
        </p>
        <p className="mt-2">
          To request a refund, please contact Paddle directly through their{" "}
          <a href="https://paddle.net" className="text-blue-600 underline">
            support form
          </a>
          .
        </p>
        <p className="mt-2">
          Refunds may be refused in cases of fraud, abuse, or misuse. This does
          not affect your rights as a consumer under applicable law.
        </p>
      </section>

      <section className="mb-10">
        <h2 className="text-xl font-semibold mb-2">
          8. Third-Party Payment Processor
        </h2>
        <p>
          Our order process is conducted by our online reseller{" "}
          <a href="https://www.paddle.com" className="text-blue-600 underline">
            Paddle.com
          </a>
          .<strong> Paddle.com is the Merchant of Record</strong> for all our
          orders. Paddle provides all customer service inquiries and handles
          returns.
        </p>
        <p className="mt-2">
          We do not store or have access to your payment information. Paddle is
          fully PCI DSS compliant.
        </p>
      </section>

      <section className="mb-10">
        <h2 className="text-xl font-semibold mb-2">9. Privacy Policy</h2>
        <ul className="list-disc list-inside space-y-1">
          <li>
            We collect your email address and uploaded PDF files to operate the
            service.
          </li>
          <li>
            Uploaded documents are processed securely and are never shared with
            third parties.
          </li>
          <li>
            Summaries may be stored anonymously to improve our AI performance.
          </li>
          <li>
            We use third-party services such as <strong>Clerk</strong>{" "}
            (authentication) and <strong>Paddle</strong> (payments).
          </li>
          <li>
            You can request data deletion by emailing us at{" "}
            <a
              href="mailto:radhakrishn0181@gmail.com"
              className="text-blue-600 underline"
            >
              radhakrishn0181@gmail.com
            </a>
            .
          </li>
        </ul>
      </section>

      <section className="mb-10">
        <h2 className="text-xl font-semibold mb-2">10. Contact Us</h2>
        <p>
          If you have any questions or concerns about these terms, please reach
          out to us:
        </p>
        <p className="mt-1">
          📧{" "}
          <a
            href="mailto:radhakrishn0181@gmail.com"
            className="text-blue-600 underline"
          >
            radhakrishn0181@gmail.com
          </a>
        </p>
      </section>

      <section className="mb-10">
        <h2 className="text-xl font-semibold mb-2">11. Governing Law</h2>
        <p>
          These Terms shall be governed by the laws of India. Any disputes
          arising under these Terms shall be subject to the jurisdiction of
          Indian courts.
        </p>
      </section>

      <section className="border-t border-gray-300 pt-6 text-sm text-gray-600">
        <p>🔗 Quick Links:</p>
        <ul className="list-disc list-inside">
          <li>
            <a href="#privacy-policy" className="text-blue-600 underline">
              Privacy Policy
            </a>
          </li>
          <li>
            <a href="#refund-policy" className="text-blue-600 underline">
              Refund Policy
            </a>
          </li>
          <li>
            <a href="#contact-us" className="text-blue-600 underline">
              Contact Us
            </a>
          </li>
        </ul>
      </section>
    </main>
  );
}
